config/routes.rb
Rails.application.routes.draw do
  devise_for :user
  authenticate :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "blazer"
  end
  root to: "pages#index"
  resources :vehicles
  get "/pages/*page", to: 'pages#show'
  authenticated :user do
    root to: "vehicles#index", as: :authenticated_root
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ahoy/event.rb
class Ahoy::Event < ApplicationRecord
  include Ahoy::QueryMethods

  self.table_name = "ahoy_events"

  belongs_to :visit
  belongs_to :user, optional: true
end

app/models/ahoy/visit.rb
class Ahoy::Visit < ApplicationRecord
  self.table_name = "ahoy_visits"

  has_many :events, class_name: "Ahoy::Event"
  belongs_to :user, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :lockable, :timeoutable, :trackable
  has_many :vehicles
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :user
  has_many_attached :images
  has_many_attached :documents
  has_rich_text :notes
  enum fuel_types: {
    petrol: 'petrol',
    diesel: 'diesel',
    bi_fuel: 'bi_fuel',
    electric: 'electric',
    hybrid_diesel_electric: 'hybrid_diesel_electric',
    hybrid_diesel_electric_plug_in: 'hybrid_diesel_electric_plug_in',
    hybrid_petrol_electric: 'hybrid_petrol_electric',
    hybrid_petrol_electric_plug_in: 'hybrid_petrol_electric_plug_in',
    ethanol: 'ethanol'
  }, _suffix: true
  enum gearboxes: {
    manual: 'manual',
    automatic: 'automatic',
    semi_automatic: 'semi_automatic'
  }, _suffix: true
  enum body_types: {
    MPV: 'MPV',
    Convertible: 'Convertible',
    SUV: 'SUV',
    Estate: 'Estate',
    Hatchback: 'Hatchback',
    Coupe: 'Coupe',
    Pickup: 'Pickup',
    Saloon: 'Saloon',
    Van: 'Van',
    Truck: 'Truck',
    Bike: 'Bike',
    Motorhome: 'Motorhome'
  }, _suffix: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/set_current_host_for_disk_service.rb
module SetCurrentHostForDiskService
  extend ActiveSupport::Concern

  included do
    before_action :set_current_host_for_disk_service, if: -> {ActiveStorage::Blob.service.is_a?(ActiveStorage::Service::DiskService)}
  end

  private

  def set_current_host_for_disk_service
    ActiveStorage::Current.host = request.base_url
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    render template: "pages/index"
  end

  def show
    if valid_page?
      render template: "pages/#{params[:page]}"
    else
      render file: "public/404.html", status: :not_found
    end
  end

  def allowed_params
    params.require(:pages)
  end

  def valid_page?
    File.exists?(Pathname.new(Rails.root + "app/views/pages/#{params[:page]}.html.erb"))
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  include SetCurrentHostForDiskService
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = current_user.vehicles
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)
    @vehicle.user = current_user

    respond_to do |format|
      if @vehicle.save
        format.html {redirect_to @vehicle, notice: 'Vehicle was successfully created.'}
        format.json {render :show, status: :created, location: @vehicle}
      else
        format.html {render :new}
        format.json {render json: @vehicle.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html {redirect_to @vehicle, notice: 'Vehicle was successfully updated.'}
        format.json {render :show, status: :ok, location: @vehicle}
      else
        format.html {render :edit}
        format.json {render json: @vehicle.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html {redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_vehicle
    @vehicle = Vehicle.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def vehicle_params
    params.require(:vehicle).permit(
        :name,
        :registration,
        :make,
        :model,
        :trim,
        :year,
        :notes,
        :mileage,
        :mot_expires,
        :insurance_expires,
        :fuel_type,
        :body_type,
        :gearbox,
        :doors,
        :colour,
        :fuel_consumption,
        :engine_size,
        documents: [],
        images: []
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_fit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Krmb</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'bootstrap', 'data-turbolinks-track': 'reload' %>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <script>
      Userback = window.Userback || {};
      Userback.access_token = '4884|6714|306c0A5bzcFWMlPtkUR2663TplqOVhlipDwvTtw3ezqrmhOMmc';

      (function (id) {
          if (document.getElementById(id)) {
              return;
          }
          var s = document.createElement('script');
          s.id = id;
          s.async = 1;
          s.src = 'https://static.userback.io/widget/v1.js';
          var parent_node = document.head || document.body;
          parent_node.appendChild(s);
      })('userback-sdk');
  </script>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="<%= root_path %>">¡Karamba!</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if current_user.try(:admin?) %>
        <li class="nav-item">
          <%= link_to('Dashboard', blazer.root_path, class:'nav-link') %>
        </li>
      <% end %>
      <li class="nav-item">
        <%= link_to('My Vehicles', vehicles_path, class: 'nav-link') %>
      </li>
    </ul>
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link") %>
        </li>
      <% elsif !current_page?(new_user_registration_path) %>
        <li class="nav-item">
          <%= link_to('Register', new_user_registration_path, class: "nav-link") %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="loginDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Login
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="loginDropdown">
            <%= form_for(:user, url: session_path(:user), html: {class: 'px-2 py-3 small'}) do |f| %>
              <div class="form-group">
                <%= f.label :email, class: 'sr-only' %>
                <%= f.text_field :email, class: 'form-control mr-sm-2', placeholder: 'email', required: true %>
              </div>
              <div class="form-group">
                <%= f.label :password, class: 'sr-only' %>
                <%= f.password_field :password, class: 'form-control mr-sm-2', placeholder: 'password', required: true %>
              </div>
              <%= f.check_box :remember_me %>
              <%= f.label :remember_me %>
              <%= f.submit 'Sign in', class: 'btn btn-primary btn-block' %>
            <% end %>
            <div class="dropdown-divider"></div>
            <%= link_to('Register', new_user_registration_path, class: "dropdown-item") %>
            <%= link_to "Forgot your password?", new_password_path(:user), class: 'dropdown-item' %>
          </div>
        </li>
        </ul>
      <% end %>
      </div>
</nav>
<div class="container">
  <% if notice %>
    <div class="alert alert-info alert-dismissible fade show my-2" role="alert">
      <%= notice %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-danger alert-dismissible fade show my-2" role="alert">
      <%= alert %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
  <%= yield %>
</div>
</body>
</html>

app/views/pages/index.html.erb
<div class="jumbotron bg-white my-4">
  <h1 class="display-4">When is your MOT due? <br/> When does your insurance expire? <br/> What tyre size do you need?
    <br/> Didn't you get new pads & discs last year!?</h1>
  <p class="lead">¡Ay, Karamba!</p>
  <hr class="my-4">
  <p>If, like me, you struggle to keep track of all your vehicle minutiae; If you're sick of having to rifle through old
    MOT certificates and service receipts, then you've come to the right place. </p>
  <p>Karamba is a simple app to store everything you need to know about your vehicles, so it's just a tap away when you
    need it.</p>
  <a class="btn btn-outline-primary btn-lg" href="<%= new_user_registration_path %>" role="button">Get organised</a>
</div>

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle, local: true) do |form| %>
  <% if vehicle&.errors&.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
        <% vehicle.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= form.label :name, class: 'sr-only' %>
        <%= form.text_field :name, class: 'form-control', placeholder: 'Name' %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= form.label :registration, class: 'sr-only' %>
        <%= form.text_field :registration, class: 'form-control', placeholder: 'Registration' %>
      </div>
    </div>
    <div class="col-6 col-md-2">
      <div class="form-group">
        <%= form.label :year, class: 'sr-only' %>
        <%= form.number_field :year, class: 'form-control', placeholder: 'Year' %>
      </div>
    </div>
    <div class="col-6 col-md-2">
      <div class="form-group">
        <%= form.label :mileage, class: 'sr-only' %>
        <%= form.number_field :mileage, class: 'form-control', placeholder: 'Mileage' %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= form.label :make, class: 'sr-only' %>
        <%= form.text_field :make, class: 'form-control', placeholder: 'Make' %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= form.label :model, class: 'sr-only' %>
        <%= form.text_field :model, class: 'form-control', placeholder: 'Model' %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= form.label :trim, class: 'sr-only' %>
        <%= form.text_field :trim, class: 'form-control', placeholder: 'Trim' %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= form.label :colour, class: 'sr-only' %>
        <%= form.text_field :colour, class: 'form-control', placeholder: 'Colour' %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= form.label :doors, class: 'sr-only' %>
        <%= form.number_field :doors, class: 'form-control', placeholder: 'Doors' %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= form.label :body_type, class: 'sr-only' %>
        <%= form.select(:body_type, Vehicle.body_types, {prompt: 'Body Type'}, {class: 'custom-select', required: true }) %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2">
      <div class="form-group">
        <%= form.label :fuel_consumption, 'MPG', class: 'sr-only' %>
        <%= form.number_field :fuel_consumption, class: 'form-control', placeholder: 'MPG' %>
      </div>
    </div>
    <div class="col-md-2">
      <div class="form-group">
        <%= form.label :engine_size, class: 'sr-only' %>
        <%= form.number_field :engine_size, class: 'form-control', placeholder: 'Engine Size' %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= form.label :fuel_type, class: 'sr-only' %>
        <%= form.select(:fuel_type, Vehicle.fuel_types, {prompt: 'Fuel Type'}, {class: 'custom-select', required: true }) %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= form.label :gearbox, class: 'sr-only' %>
        <%= form.select(:gearbox, Vehicle.gearboxes, {prompt: 'Gearbox'}, {class: 'custom-select', required: true }) %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :mot_expires, 'MOT expires' %>
        <div class="input-group">
          <%= form.date_select :mot_expires, {placeholder: 'MOT Expiry Date'}, class: 'custom-select' %>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :insurance_expires %>
        <div class="input-group">
          <%= form.date_select :insurance_expires, {placeholder: 'Insurance Expiry Date'}, class: 'custom-select' %>
        </div>
      </div>
    </div>
  </div>

  <div class="form-group d-none d-md-block">
    <%= form.label :notes %>
    <%= form.rich_text_area :notes, class: 'form-control', placeholder: 'Notes' %>
  </div>

  <div class="form-group">
    <div class="custom-file">
      <%= form.label :documents, class: 'custom-file-label' %>
      <%= form.file_field :documents, multiple: true, direct_upload: true, class: 'custom-file-input', placeholder: 'Documents' %>
    </div>
  </div>
  <div class="form-group">
    <div class="custom-file">
      <%= form.label :images, class: 'custom-file-label' %>
      <%= form.file_field :images, multiple: true, direct_upload: true, class: 'custom-file-input', placeholder: 'Images' %>
    </div>
  </div>

  <div class="d-flex justify-content-between align-items-center my-2">
    <%= link_to 'Back', vehicles_path %>
    <%= form.submit class: 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<div class="d-flex justify-content-between align-items-center">
  <h1 class="">Vehicles</h1>
  <%= link_to 'New Vehicle', new_vehicle_path, class: 'btn btn-outline-primary' %>
</div>

<div class="card-columns">
    <% @vehicles&.each do |vehicle| %>
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= "#{vehicle.registration}" %></h5>
          <h6 class="card-subtitle mb-2 text-muted"><%= "#{vehicle.make} #{vehicle.model}" %></h6>
          <%= link_to 'Show', vehicle, class: 'card-link' %>
          <%= link_to 'Edit', edit_vehicle_path(vehicle), class: 'card-link' %>
          <%= link_to 'Destroy', vehicle, method: :delete, data: {confirm: 'Are you sure?'}, class: 'card-link' %>
        </div>
      </div>
    <% end%>
  </div>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

app/views/vehicles/show.html.erb
<div class="row my-4">
  <div class="col-md-7 d-flex justify-content-center justify-content-md-start">
    <div>
      <h1 class="text-center text-md-left"><%= @vehicle.name %></h1>
      <p class="lead text-center text-md-left my-0"><%= "#{@vehicle.year} #{@vehicle.make} #{@vehicle.model} #{@vehicle.doors}-door #{@vehicle.body_type}" %></p>
      <p class="text-muted text-center text-md-left"><%= "#{@vehicle.engine_size} #{@vehicle.fuel_type} #{@vehicle.gearbox}" %></p>
    </div>
  </div>
  <div class="col-md-5 d-flex justify-content-center justify-content-md-end align-items-top">
    <div>
      <span class="registration-ui"><%= @vehicle.registration %></span>
    </div>
  </div>
</div>
<ul class="nav nav-tabs" id="navTabs" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="details-tab" data-toggle="tab" href="#details" role="tab" aria-controls="details" aria-selected="true">Details</a>
  </li>
  <li class="nav-item">
    <a href="#legal" class="nav-link" id="legal-tab" data-toggle="tab" role="tab" aria-controls="legal" aria-selected="false">Legal</a>
  </li>
  <li class="nav-item">
    <a href="#notes" class="nav-link" id="notes-tab" data-toggle="tab" role="tab" aria-controls="notes" aria-selected="false">Notes</a>
  </li>
  <li class="nav-item">
    <a href="#documents" class="nav-link" id="documents-tab" data-toggle="tab" role="tab" aria-controls="documents" aria-selected="false">Documents</a>
  </li>
  <li class="nav-item">
    <a href="#photos" class="nav-link" id="photos-tab" data-toggle="tab" role="tab" aria-controls="photos" aria-selected="false">Photos</a>
  </li>
</ul>
<div class="tab-content" id="navTabsContent">
  <div class="tab-pane fade show active" id="details" role="tabpanel" aria-labelledby="#details-tab">
    <p>
      <strong>Trim:</strong>
      <%= @vehicle.trim %>
    </p>
    <p>
      <strong>Colour:</strong>
      <%= @vehicle.colour %>
    </p>
    <p>
      <strong>Mileage:</strong>
      <%= @vehicle.mileage %>
    </p>
    <p>
      <strong>Fuel Consumption:</strong>
      <%= @vehicle.fuel_consumption %>
    </p>
  </div>
  <div class="tab-pane fade" id="legal" role="tabpanel" aria-labelledby="#legal-tab">
    <p>
      <strong>Mot expires:</strong>
      <%= @vehicle.mot_expires %>
    </p>

    <p>
      <strong>Insurance expires:</strong>
      <%= @vehicle.insurance_expires %>
    </p>
  </div>
  <div class="tab-pane fade" id="notes" role="tabpanel" aria-labelledby="#notes-tab">
    <p>
      <strong>Notes:</strong>
      <%= @vehicle.notes %>
    </p>
  </div>
  <div class="tab-pane fade" id="documents" role="tabpanel" aria-labelledby="#documents-tab">
    <p>
      <strong>Documents:</strong>
      <% @vehicle.documents.each do |d| %>
        <%= link_to('file', url_for(d)) %>
      <% end %>
    </p>
  </div>
  <div class="tab-pane fade" id="photos" role="tabpanel" aria-labelledby="#photos-tab">
    <p>
      <strong>Images:</strong>
      <% @vehicle.images.each do |i| %>
        <%= image_tag(i.variant(resize_to_limit: [200,200]).processed.service_url, class: 'img-thumbnail') %>
      <% end %>
    </p>
  </div>
</div>






<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>